version: '3'

services:
  db:
    image: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_DB=os.getenv(DATABASES_NAME)
      - POSTGRES_USER=os.getenv(DATABASES_USER)
      - POSTGRES_PASSWORD=os.getenv(DATABASES_PASSWORD)
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - '8011:8000'
    depends_on:
      db:
        condition: service_healthy

volumes:
  pg_data: